DONE: >> FP’s Inspector unable to generate file info because of a bug in CsvPath. AttributeError: 'NoneType' object has no attribute 'filename'    2 changes in CsvPath.py:       ~1341:  if self.scanner and self.scanner.filename: 	~ 1370:  lm, headers = lc.get_lines_and_headers(filename) DONE: >>> Results manager ~537 should return [] if not raising exception                 if self.csvpaths.ecoms.do_i_raise():                     raise InputException(msg)                 return [] DONE: also ~ same place: if there are > 1 len(results.files) we need to minimally log that fact since we are only handling the first found DONE: >>   Resultsmanager. def get_printouts(self, name: str, printstream: str = "default") -> dict: returns a list[str], not a dict.